In [3]:
 import numpy as np

In [9]:
arr = np.array([3,6,34,56], np.int64)

In [7]:
arr

array([ 3,  6, 34, 56], dtype=int8)

In [11]:
arr[0]

3

In [13]:
arr.shape

(4,)

In [15]:
arr.dtype

dtype('int64')

In [19]:
listarray = np.array([[2,4,5],[5,6,7],[7,3,5]])

In [21]:
listarray.dtype

dtype('int64')

In [25]:
listarray.shape

(3, 3)

In [27]:
zeros = np.zeros((3,4))

In [29]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
zeros.dtype

dtype('float64')

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
lspace = np.linspace(1,50,10)

In [37]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [39]:
emp = np.empty((4,6))

In [41]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.67293691e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 7.56601165e-307],
       [1.69118787e-306, 1.11261027e-306, 1.78018403e-306,
        8.01097889e-307, 1.11261570e-306, 1.78021527e-306],
       [1.69120824e-306, 1.05700515e-307, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [45]:
emp_like = np.empty_like(lspace)

In [48]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [50]:
ide = np.identity(45)

In [52]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [54]:
arr = np.arange(99)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [68]:
arr = arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [66]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [70]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [74]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
ar.sum(axis=0)

array([12, 15, 18])

In [78]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [80]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
ar.flat

In [84]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [86]:
ar.ndim

2

In [88]:
ar.size

9

In [90]:
ar.nbytes

36

In [104]:
one = np.array([1,992,3,95])

In [106]:
one.argmax()

1

In [108]:
one.argmin()

0

In [110]:
one.argsort()

array([0, 2, 3, 1], dtype=int64)

In [112]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
ar.argmin()

0

In [118]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [120]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
ar2=np.array([[13, 2, 3],
       [4, 54, 6],
       [71, 8, 9]])

In [126]:
ar2

array([[13,  2,  3],
       [ 4, 54,  6],
       [71,  8,  9]])

In [128]:
ar+ar2

array([[14,  4,  6],
       [ 8, 59, 12],
       [78, 16, 18]])

In [130]:
ar*ar2

array([[ 13,   4,   9],
       [ 16, 270,  36],
       [497,  64,  81]])

In [132]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [134]:
arr.sum()

4851

In [136]:
arr.max()

98

In [138]:
arr.min()

0

In [140]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [144]:
type(np.where(ar>5))

tuple

In [146]:
np.count_nonzero(ar)

9

In [150]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [152]:
ar 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
ar[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
arr[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [158]:
ar[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
ar[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
arr[1:2]

array([[33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65]])

In [164]:
ar[1:2]

array([[4, 5, 6]])

In [166]:
ar[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [168]:
one = np.array([10,20,30,40])
two = np.array([50,60,70,80])

In [170]:
np.add(one,two)

array([ 60,  80, 100, 120])

In [172]:
np.subtract(two,one)

array([40, 40, 40, 40])

In [174]:
np.multiply(one,two)

array([ 500, 1200, 2100, 3200])

In [176]:
np.divide(one,two)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [178]:
power = np.array([3])

In [180]:
np.power(one,power)

array([ 1000,  8000, 27000, 64000])

In [182]:
np.sqrt(two)

array([7.07106781, 7.74596669, 8.36660027, 8.94427191])

In [184]:
# concatenate

In [186]:
np.concatenate([one,two])

array([10, 20, 30, 40, 50, 60, 70, 80])

In [190]:
arr1 = np.array([[6,5,4,3],[4,5,3,2]])
arr2 = np.array([[3,6,2,8],[2,9,4,6]])


In [192]:
np.hstack([arr1,arr2])

array([[6, 5, 4, 3, 3, 6, 2, 8],
       [4, 5, 3, 2, 2, 9, 4, 6]])

In [194]:
np.vstack([arr1,arr2])

array([[6, 5, 4, 3],
       [4, 5, 3, 2],
       [3, 6, 2, 8],
       [2, 9, 4, 6]])

In [204]:
a = np.array([34,55,67,42,89,32])

In [206]:
b = np.array_split(a,3)

In [208]:
b[2]

array([89, 32])

In [210]:
np.append(a,67)

array([34, 55, 67, 42, 89, 32, 67])

In [212]:
np.insert(a,4,99)

array([34, 55, 67, 42, 99, 89, 32])

In [214]:
np.delete(a,3)

array([34, 55, 67, 89, 32])

In [216]:
np.sort(a)

array([32, 34, 42, 55, 67, 89])

In [222]:
s = np.where(a==55)

In [224]:
s

(array([1], dtype=int64),)

In [226]:
k = np.where(a%2 == 0)

In [228]:
k

(array([0, 3, 5], dtype=int64),)

In [238]:
fa = [True, False,True, False,True,True]

In [240]:
new = a[fa]

In [243]:
new

array([34, 67, 89, 32])

In [246]:
a.mean()

53.166666666666664

In [252]:
np.median(a)

48.5

In [254]:
a.var()

403.1388888888889